name: Build

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 23.6.0

    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Lint
      run: npm run lint
      shell: bash
